[tool.black]
target-version = ["py310"] # Минимальная версия Python
include = '\.pyi?$'        # Проверять только .py/.pyi файлы
exclude = '''
/(
    \.git
    | \.venv
    | __pycache__
    | build
    | dist
)/
'''