name: Lint and Format

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install black flake8 flake8-bugbear

      - name: Run Black
        run: black --check .

      - name: Run flake8
        run: flake8 .